export enum CouponsTokenEnum {
    COUPONS_REPOSITORY_TOKEN = 'COUPONS_REPOSITORY_TOKEN',
    COUPONS_USER_REPOSITORY_TOKEN = 'COUPONS_USER_REPOSITORY_TOKEN',
    COUPONS_SERVICE_TOKEN = 'COUPONS_SERVICE_TOKEN',
}
